import { TripServiceType } from "@/lib/shared/types/trip-service-type.type";

export interface ApiCreateTripPayload {
  origin: string;
  destination: string;
  departure: string;
  arrival?: string;
  serviceType: TripServiceType;
  vehicleId?: string;
  capacity?: number;
  minPassengers?: number;
  autoGenerated?: boolean;
  basePrice: number;
}