export interface TripResponse {
    id: string;
    basePrice: number;
    origin: string;
    destination: string;
    departure: string;
    arrival: string;
    originalTimeZone: string;
    serviceType: "SIMPLE_TRIP" | string;
    capacity: number;
    minPassengers: number;
    status: "PENDING" | "CONFIRMED" | "CANCELLED";
    originLocation: string;
    destinationLocation: string;
}

export interface TripDetailsResponse {
    id: string;
    basePrice: number;
    origin: string;
    destination: string;
    departure: string;
    arrival: string;
    originalTimeZone: string;
    serviceType: string;
    vehicleId: string | null;
    capacity: number;
    minPassengers: number;
    status: "PENDING" | "CONFIRMED" | "CANCELLED";
    autoGenerated: boolean;
    createdAt: string;
    originLocation: string;
    destinationLocation: string;
    passengers: {
        id: string; // reservation id
        userId: string;
        fullName: string; // nombre + apellido
        email: string;
        status: "PENDING" | "CONFIRMED" | "CANCELLED";
        paymentMethod: "CASH" | "CARD" | string;
    }[];
    reservations?: {
        id: string;
        userId: string;
        fullName: string; // nombre + apellido
        email: string;
        status: "PENDING" | "CONFIRMED" | "CANCELLED";
        paymentMethod: "CASH" | "CARD" | string;
    }[];
}
