import { CreateTripPayload } from "../trip/trip.types";
import { CreateReservationPayload, PreviewReservationPayload, ReservationPreview } from "./reservation.types";

export const previewReservation = async (
  data: PreviewReservationPayload
): Promise<ReservationPreview> => {
  const res = await fetch('/api/reservation/preview', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(data),
  });

  if (!res.ok) throw new Error('No se pudo calcular el precio final');
  return res.json();
};

export const createReservation = async (
  data: CreateReservationPayload
): Promise<{ id: string }> => {
  const res = await fetch('/api/reservation', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(data),
  });

  if (!res.ok) throw new Error('Error al crear la reserva');
  return res.json();
};

export async function getTripsWithFallback(filters: {
  origin: string;
  destination: string;
  date: string;
  serviceType: string;
}) {
  const params = new URLSearchParams(filters).toString();
  const res = await fetch(`/api/trip/search?${params}`);
  const trips = await res.json();

  if (trips.length > 0) return trips;

  const createRes = await fetch("/api/trip", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      ...filters,
      departure: filters.date,
      basePrice: 27.5,
      autoGenerated: true,
    } as CreateTripPayload),
  });

  const createdTrip = await createRes.json();
  return [createdTrip];
}
