"use client";

import React, { useEffect, useState } from "react";
import { X } from "lucide-react";
import { toast } from "sonner";
import { createTrip } from "@/lib/api/admin/trips";
import { CreateTripRequest, TripResponse, TripServiceType, TripStatus } from "@/lib/api/admin/trips/trips.type";
import { DateTime } from "luxon";
import { useSession } from "next-auth/react";
import CityAutocomplete from "@/components/common/CityAutocomplete";

interface Props {
  onClose: () => void;
  onSuccess?: (newTrip: TripResponse) => void;
}

const inputClass =
  "w-full border border-custom-gray-300 rounded-md px-4 py-2 focus:outline-none focus:ring-2 focus:ring-custom-golden-400 transition";
const labelClass = "block text-xs font-semibold text-custom-gray-500 mb-1 uppercase tracking-wide";

export default function CreateTripModalPartner({ onClose, onSuccess }: Props) {
  const { data: session } = useSession();
  const [submitting, setSubmitting] = useState(false);
  const [form, setForm] = useState<CreateTripRequest>({
    origin: "",
    destination: "",
    departure: "",
    arrival: "",
    originalTimeZone: "Europe/Madrid",
    serviceType: "SIMPLE_TRIP",
    basePrice: "",
    vehicleId: undefined,
    capacity: undefined,
    minPassengers: undefined,
    autoGenerated: false,
    status: "PENDING",
    originLocation: "",
    destinationLocation: "",
    visible: true,
    driverId: "", // se setea automáticamente con el usuario partner
  });

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => {
    const { name, type, value } = e.target;

    const integerFields = ["capacity", "minPassengers"];
    const decimalFields = ["basePrice"];
    let parsedValue: string | number | boolean = value;

    if (integerFields.includes(name)) {
      if (/^\d*$/.test(value)) {
        parsedValue = value === "" ? "" : Number(value);
      } else {
        return; // ignorar input inválido
      }
    } else if (decimalFields.includes(name)) {
      const normalizedValue = value.replace(/,/g, ".");
      if (/^\d*\.?\d*$/.test(normalizedValue)) {
        parsedValue = normalizedValue;
      } else {
        return; // ignorar input inválido
      }
    } else if (type === "checkbox") {
      parsedValue = (e.target as HTMLInputElement).checked;
    }

    setForm((prev) => ({ ...prev, [name]: parsedValue }));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!session?.user?.id) {
      toast.error("No se pudo identificar al usuario. Inicia sesión nuevamente.");
      return;
    }

    const toastId = toast.loading("Creando viaje...");
    setSubmitting(true);

    const departureUTC = DateTime.fromISO(form.departure, { zone: "Europe/Madrid" }).toUTC().toISO();
    const arrivalUTC = DateTime.fromISO(form.arrival, { zone: "Europe/Madrid" }).toUTC().toISO();

    const payload: CreateTripRequest = {
      ...form,
      origin: form.origin.trim(),
      destination: form.destination.trim(),
      departure: departureUTC || form.departure,
      arrival: arrivalUTC || form.departure,
      basePrice: parseFloat(form.basePrice as string),
      driverId: session.user.id, // asignar automáticamente el driver al partner
    };

    try {
      const res = await createTrip(payload);
      toast.success("Viaje creado con éxito", { id: toastId });
      onSuccess?.(res);
      onClose();
    } catch (error) {
      console.error(error);
      toast.error("Error al crear el viaje", { id: toastId });
    } finally {
      setSubmitting(false);
    }
  };

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === "Escape") {
        onClose();
      }
    };

    window.addEventListener("keydown", handleKeyDown);
    return () => {
      window.removeEventListener("keydown", handleKeyDown);
    };
  }, [onClose]);

  return (
    <div className="fixed inset-0 bg-transparent backdrop-blur-sm bg-opacity-70 flex justify-center items-center z-50">
      <div
        onClick={(e) => e.stopPropagation()}
        className="bg-white rounded-xl shadow-2xl p-8 my-8 w-full max-w-4xl max-h-[95vh] overflow-y-auto relative border border-custom-gray-300"
      >
        <button onClick={onClose} className="cursor-pointer absolute top-4 right-4 text-gray-500 hover:text-black" aria-label="Cerrar">
          <X className="size-5" />
        </button>

        <h2 className="text-2xl font-bold mb-2 text-custom-golden-700">Publicar nuevo viaje</h2>
        <p className="text-sm text-custom-gray-500 mb-6">Completa los datos a continuación para publicar tu viaje.</p>

        <form onSubmit={handleSubmit} className="grid grid-cols-1 md:grid-cols-2 gap-5 text-sm text-custom-black-800">
          <div className="col-span-full">
            <h3 className="text-base font-semibold text-custom-golden-600 mb-1">Ubicación y horario</h3>
            <hr className="mb-4" />
          </div>

          <div>
            <label className={labelClass}>Origen</label>
            <CityAutocomplete
              value={form.origin}
              onChange={(val, meta) => {
                const onlyCity = meta?.payload?.name || (val || "").split(",")[0]?.trim() || val;
                setForm((prev) => ({ ...prev, origin: onlyCity }));
              }}
              placeholder="Ciudad de origen"
              allowFreeText
            />
          </div>

          <div>
            <label className={labelClass}>Destino</label>
            <CityAutocomplete
              value={form.destination}
              onChange={(val, meta) => {
                const onlyCity = meta?.payload?.name || (val || "").split(",")[0]?.trim() || val;
                setForm((prev) => ({ ...prev, destination: onlyCity }));
              }}
              placeholder="Ciudad de destino"
              allowFreeText
            />
          </div>

          {["departure", "arrival", "originalTimeZone", "originLocation", "destinationLocation"].map((name) => (
            <div key={name}>
              <label className={labelClass}>{name}</label>
              <input
                name={name}
                type={name === "departure" || name === "arrival" ? "datetime-local" : "text"}
                value={
                  typeof form[name as keyof CreateTripRequest] === "boolean"
                    ? ""
                    : (form[name as keyof CreateTripRequest] as string | number) || ""
                }
                onChange={handleChange}
                className={inputClass}
                required
              />
            </div>
          ))}

          <div className="col-span-full mt-6">
            <h3 className="text-base font-semibold text-custom-golden-600 mb-1">Configuración del viaje</h3>
            <hr className="mb-4" />
          </div>

          <div>
            <label className={labelClass}>Tipo de servicio</label>
            <select name="serviceType" value={form.serviceType} onChange={handleChange} className={`${inputClass}`} disabled>
              {Object.values(TripServiceType).map((type) => (
                <option key={type} value={type}>
                  {type}
                </option>
              ))}
            </select>
          </div>

          <div>
            <label className={labelClass}>Estado</label>
            <select name="status" value={form.status} onChange={handleChange} className={inputClass}>
              {Object.values(TripStatus).map((status) => (
                <option key={status} value={status}>
                  {status}
                </option>
              ))}
            </select>
          </div>

          <div>
            <label className={labelClass}>Precio base (€)</label>
            <input type="text" name="basePrice" value={form.basePrice} onChange={handleChange} className={inputClass} required />
          </div>

          <div>
            <label className={labelClass}>Capacidad</label>
            <input type="text" name="capacity" value={form.capacity ?? ""} onChange={handleChange} className={inputClass} />
          </div>

          <div>
            <label className={labelClass}>Mín. pasajeros</label>
            <input type="text" name="minPassengers" value={form.minPassengers ?? ""} onChange={handleChange} className={inputClass} />
          </div>

          <div className="col-span-full flex flex-wrap items-center gap-6 mt-2">
            <label className="flex items-center text-xs font-medium">
              <input type="checkbox" name="visible" checked={form.visible} onChange={handleChange} className="mr-2" />
              Visible al público
            </label>
          </div>

          <div className="col-span-full flex justify-end gap-3 mt-8">
            <button
              type="button"
              onClick={onClose}
              className="cursor-pointer border border-custom-gray-300 text-custom-black-800 hover:bg-custom-gray-100 font-medium py-2 px-5 rounded-md"
              disabled={submitting}
            >
              Cancelar
            </button>
            <button
              type="submit"
              className="cursor-pointer bg-custom-golden-600 hover:bg-custom-golden-700 text-white font-semibold py-2 px-5 rounded-md disabled:opacity-50"
              disabled={submitting || !form.origin || !form.destination || !form.departure || !form.arrival || !form.basePrice}
            >
              {submitting ? "Creando..." : "Crear viaje"}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
