import { BACKEND_URL } from "@/lib/constants";
import { fetchWithAuth } from "@/lib/functions";
import { Pencil, Trash2 } from "lucide-react";
import { useEffect, useState } from "react";
import SkeletonTable from "../SkeletonTable";
import { SimpleTrip, TripResponse } from "@/lib/api/admin/trips/trips.type";

export default function TripsPanel() {
    const [trips, setTrips] = useState<SimpleTrip[]>([]);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        const fetchTrips = async () => {
            try {
                const res = await fetchWithAuth(`${BACKEND_URL}/trip/all`);
                if (!Array.isArray(res)) {
                    throw new Error("La respuesta del backend no es un array de viajes");
                }
                const mapped = res.map(
                    (trip: TripResponse): SimpleTrip => ({
                        id: trip.id,
                        origin: trip.origin,
                        destination: trip.destination,
                        originLocation: trip.originLocation,
                        destinationLocation: trip.destinationLocation,
                        departure: trip.departure,
                        arrival: trip.arrival,
                        basePrice: trip.basePrice,
                        capacity: trip.capacity,
                        minPassengers: trip.minPassengers,
                        status: trip.status,
                        serviceType: trip.serviceType,
                        autoGenerated: trip.autoGenerated,
                        visible: trip.visible,
                    })
                );
                setTrips(mapped);
            } catch (error) {
                console.error("Error al cargar viajes:", error);
            } finally {
                setLoading(false);
            }
        };
        fetchTrips();
    }, []);

    return (
        <div className="w-full h-full flex flex-col overflow-hidden pb-2">
            <h1 className="text-2xl font-bold mb-4 text-custom-golden-600">Panel de Viajes</h1>

            {loading ? (
                <SkeletonTable rows={5} />
            ) : (
                <div className="flex-1 w-full bg-custom-white-100 rounded-xl shadow-sm border border-custom-gray-200 overflow-hidden flex flex-col">
                    <table className="min-w-full text-sm text-left table-fixed border-separate border-spacing-0">
                        <thead className="bg-custom-golden-100 text-custom-golden-700 uppercase text-xs">
                            <tr>
                                <th className="px-4 py-2 border-b border-r border-custom-gray-300">Origen</th>
                                <th className="px-4 py-2 border-b border-r border-custom-gray-300">Destino</th>
                                <th className="px-4 py-2 border-b border-r border-custom-gray-300">Salida</th>
                                <th className="px-4 py-2 border-b border-r border-custom-gray-300">Llegada</th>
                                <th className="px-4 py-2 border-b border-r border-custom-gray-300">Precio</th>
                                <th className="px-4 py-2 border-b border-r border-custom-gray-300">Capacidad</th>
                                <th className="px-4 py-2 border-b border-r border-custom-gray-300">Estado</th>
                                <th className="px-4 py-2 border-b border-custom-gray-300 text-center">Acciones</th>
                            </tr>
                        </thead>
                        <tbody className="text-custom-black-800">
                            {trips.map((trip, index) => (
                                <tr
                                    key={trip.id}
                                    className={`${
                                        index % 2 === 0 ? "bg-custom-white-50" : "bg-custom-gray-100"
                                    } hover:bg-custom-golden-100 transition`}
                                >
                                    <td className="px-4 py-2 font-medium border-b border-r border-custom-gray-200">{trip.origin}</td>
                                    <td className="px-4 py-2 border-b border-r border-custom-gray-200">{trip.destination}</td>
                                    <td className="px-4 py-2 border-b border-r border-custom-gray-200">
                                        {new Date(trip.departure).toLocaleString()}
                                    </td>
                                    <td className="px-4 py-2 border-b border-r border-custom-gray-200">{new Date(trip.arrival).toLocaleString()}</td>
                                    <td className="px-4 py-2 border-b border-r border-custom-gray-200">€ {trip.basePrice.toFixed(2)}</td>
                                    <td className="px-4 py-2 border-b border-r border-custom-gray-200">{trip.capacity}</td>
                                    <td className="px-4 py-2 border-b border-r border-custom-gray-200">{trip.status}</td>
                                    <td className="px-4 py-2 border-b border-custom-gray-200 text-center space-x-2">
                                        <button
                                            onClick={() => console.log("Editar", trip)}
                                            className="text-custom-golden-600 hover:text-custom-golden-700"
                                            aria-label="Editar"
                                        >
                                            <Pencil className="h-4 w-4 inline-block" />
                                        </button>
                                        <button
                                            onClick={() => console.log("Eliminar", trip)}
                                            className="text-red-500 hover:text-red-700"
                                            aria-label="Eliminar"
                                        >
                                            <Trash2 className="h-4 w-4 inline-block" />
                                        </button>
                                    </td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>
            )}
        </div>
    );
}
