export interface SimpleTrip {
    id: string;
    origin: string;
    destination: string;
    originLocation: string;
    destinationLocation: string;
    departure: string;
    arrival: string;
    basePrice: number;
    capacity: number;
    minPassengers: number;
    status: "PENDING" | "CONFIRMED" | "CANCELLED";
    serviceType: "SIMPLE_TRIP" | "RENTAL_WITH_DRIVER" | "RENTAL_WITHOUT_DRIVER";
    autoGenerated: boolean;
    visible: boolean;
}

export interface TripResponse {
    id: string;
    origin: string;
    destination: string;
    originLocation: string;
    destinationLocation: string;
    departure: string;
    arrival: string;
    basePrice: number;
    capacity: number;
    minPassengers: number;
    status: "PENDING" | "CONFIRMED" | "CANCELLED";
    serviceType: "SIMPLE_TRIP" | "RENTAL_WITH_DRIVER" | "RENTAL_WITHOUT_DRIVER";
    autoGenerated: boolean;
    visible: boolean;
}
