export interface SimpleTrip {
    id: string;
    origin: string;
    destination: string;
    originLocation: string;
    destinationLocation: string;
    departure: string;
    arrival: string;
    basePrice: number;
    capacity: number;
    minPassengers: number;
    status: "PENDING" | "CONFIRMED" | "CANCELLED";
    serviceType: "SIMPLE_TRIP" | "RENTAL_WITH_DRIVER" | "RENTAL_WITHOUT_DRIVER";
    autoGenerated: boolean;
    visible: boolean;
}

export interface TripResponse {
    id: string;
    basePrice: number;
    origin: string;
    destination: string;
    departure: string;
    arrival: string;
    originalTimeZone: string;
    originLocation: string;
    destinationLocation: string;
    serviceType: "SIMPLE_TRIP" | "RENTAL_WITH_DRIVER" | "RENTAL_WITHOUT_DRIVER";
    vehicleId: string | null;
    vehicle?: {
        id: string;
        plate: string;
        capacity: number;
        serviceType: string;
        provider: string;
        allowSeatSelection: boolean;
        ownerId: string;
        createdAt: string;
        updatedAt: string;
    } | null;
    capacity: number;
    minPassengers: number;
    status: "PENDING" | "CONFIRMED" | "CANCELLED";
    autoGenerated: boolean;
    visible: boolean;
    createdAt: string;
    userId: string;
    reservations?: TripReservation[];
    driverId?: string;
    driver?: {
        id: string;
        email: string;
        name: string;
        lastName: string;
    } | null;
}

export interface Passengers {
    id: string;
    paymentMethod: string;
    status: string;
    user?: {
        id: string;
        name: string;
        lastName: string;
        email: string;
        phone?: string;
    };
    cancelReason?: string | null;
    qr?: {
        id: string;
        imageUrl: string;
        usedAt: string | null;
        isValid: boolean;
        createdAt: string;
        reservationId: string;
        isDeleted: boolean;
    };
}

export interface TripReservation {
    id: string;
    userId: string;
    tripId: string;
    seatCode: string | null;
    discountId: string | null;
    price: number;
    IVA: number;
    notes: string | null;
    paymentMethod: string;
    status: "PENDING" | "CONFIRMED" | "CANCELLED";
    createdAt: string;
    user?: {
        id: string;
        email: string;
        name: string;
        lastName: string;
        phone?: string;
    };
    cancelReason?: string | null;
}

export interface CreateTripRequest {
    id?: string;
    origin: string;
    destination: string;
    departure: string;
    arrival: string;
    originalTimeZone: string;
    serviceType: "SIMPLE_TRIP" | "RENTAL_WITH_DRIVER" | "RENTAL_WITHOUT_DRIVER";
    basePrice: number | string;
    vehicleId?: string;
    capacity?: number;
    minPassengers?: number;
    autoGenerated?: boolean;
    status?: "PENDING" | "CONFIRMED" | "CANCELLED";
    originLocation?: string;
    destinationLocation?: string;
    visible?: boolean;
    driverId?: string;
    partnerId?: string;
}

export interface UpdateTripRequest {
    id?: string;
    origin: string;
    destination: string;
    departure: string;
    arrival: string;
    originalTimeZone: string;
    serviceType: TripServiceType;
    vehicleId?: string;
    capacity?: number;
    minPassengers?: number;
    autoGenerated?: boolean;
    basePrice: number;
    status?: TripStatus;
    originLocation: string;
    destinationLocation: string;
    visible?: boolean;
    partnerId: string;
    driverId: string;
}

export enum TripServiceType {
    SIMPLE_TRIP = "SIMPLE_TRIP",
}

export enum TripStatus {
    PENDING = "PENDING",
    CONFIRMED = "CONFIRMED",
    CANCELLED = "CANCELLED",
    FINISHED = "FINISHED",
}

export interface Vehicle {
    id: string;
    plate: string;
    capacity: number;
    serviceType: string;
    provider: string;
    allowSeatSelection: boolean;
}

export interface Partner {
    id: string;
    email: string;
    name: string;
    lastName: string;
    Vehicle: Vehicle[];
}

export interface Driver {
    id: string;
    email: string;
    name: string;
    lastName: string;
}
