export const BACKEND_URL = process.env.NEXT_PUBLIC_BACKEND_URL || "http://localhost:8000";

export const LOCATIONS = [
  { value: "valencia", label: "Valencia, España" },
  { value: "madrid", label: "Madrid, España" },
  { value: "barcelona", label: "Barcelona, España" },
];

export const SERVICES = [
  { value: "SIMPLE_TRIP", label: "Viaje simple" },
  { value: "RENTAL_WITH_DRIVER", label: "Viaje con chofer" },
  { value: "RENTAL_WITHOUT_DRIVER", label: "Viaje sin chofer" },
];

export const VS_AUTOGENERATED_ROUTES = [
  { from: "Valencia", to: "Madrid", duration: 3.5 },
  { from: "Madrid", to: "Valencia", duration: 3.5 },
  { from: "Valencia", to: "Barcelona", duration: 3.5 },
  { from: "Barcelona", to: "Valencia", duration: 3.5 },
];
