import React, { Dispatch, SetStateAction, useEffect, useMemo, useState } from "react";
import { X } from "lucide-react";
import { toast } from "sonner";
import { createTrip } from "@/lib/api/admin/trips";
import { CreateTripRequest, Driver, Partner, TripResponse, TripServiceType } from "@/lib/api/admin/trips/trips.type";
import { convertUtcToDatetimeLocalInput } from "@/lib/functions";

interface Props {
  onClose: () => void;
  onSuccess: Dispatch<SetStateAction<TripResponse[]>>;
  partners: Partner[];
  drivers: Driver[];
  trip: CreateTripRequest & { user?: Partner };
}

const inputClass =
  "w-full border border-custom-gray-300 rounded-md px-4 py-2 focus:outline-none focus:ring-2 focus:ring-custom-golden-400 transition";
const labelClass = "block text-xs font-semibold text-custom-gray-500 mb-1 uppercase tracking-wide";

export default function CloneTripModal({ onClose, onSuccess, drivers, trip }: Props) {
  const initialForm: CreateTripRequest = {
    origin: trip.origin,
    destination: trip.destination,
    departure: convertUtcToDatetimeLocalInput(trip.departure, trip.originalTimeZone) || "",
    arrival: convertUtcToDatetimeLocalInput(trip.arrival, trip.originalTimeZone) || "",
    originalTimeZone: trip.originalTimeZone,
    serviceType: (trip.serviceType as TripServiceType) || "SIMPLE_TRIP",
    vehicleId: undefined,
    capacity: trip.capacity,
    minPassengers: trip.minPassengers,
    autoGenerated: false,
    basePrice: typeof trip.basePrice === "string" ? parseFloat(trip.basePrice) : (trip.basePrice as number),
    status: "PENDING",
    originLocation: trip.originLocation || "",
    destinationLocation: trip.destinationLocation || "",
    visible: trip.visible,
    // Do NOT send partnerId so backend uses current authenticated user automatically
    partnerId: "",
    driverId: trip.driverId || "",
  };

  const [form, setForm] = useState<CreateTripRequest>(initialForm);
  const allowedStatuses = ["PENDING", "CONFIRMED", "CANCELLED"] as const;
  const selectedDriver = useMemo(() => drivers.find((d) => d.id === form.driverId), [drivers, form.driverId]);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => {
    const { name, type, value } = e.target;

    const numericFields = ["capacity", "minPassengers"];
    const decimalFields = ["basePrice"];
    let parsedValue: string | number | boolean = value;

    if (numericFields.includes(name)) {
      if (/^\d*$/.test(value)) {
        parsedValue = value === "" ? "" : Number(value);
      } else {
        return; // ignora input inválido
      }
    } else if (decimalFields.includes(name)) {
      const normalizedValue = value.replace(/,/g, ".");
      if (/^\d*\.?\d*$/.test(normalizedValue)) {
        parsedValue = normalizedValue;
      } else {
        return;
      }
    } else if (type === "checkbox") {
      parsedValue = (e.target as HTMLInputElement).checked;
    }

    setForm((prev) => ({ ...prev, [name]: parsedValue }));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    const payload: CreateTripRequest = {
      ...form,
      origin: form.origin.trim(),
      destination: form.destination.trim(),
      departure: new Date(form.departure as string).toISOString(),
      arrival: new Date(form.arrival as string).toISOString(),
      capacity: typeof form.capacity === "string" ? parseInt(form.capacity) : form.capacity,
      minPassengers: typeof form.minPassengers === "string" ? parseInt(form.minPassengers) : form.minPassengers,
      basePrice: typeof form.basePrice === "string" ? parseFloat(form.basePrice) : form.basePrice,
    };

    const toastId = toast.loading("Clonando viaje...");
    try {
      const res = await createTrip(payload);
      toast.success("Viaje clonado con éxito", { id: toastId });
      onSuccess((prev) => [...prev, res]);
      onClose();
    } catch (error: any) {
      console.error(error);
      const message = (error?.message as string) || "Error al clonar el viaje";
      toast.error(message, { id: toastId });
    }
  };

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === "Escape") onClose();
    };

    window.addEventListener("keydown", handleKeyDown);
    return () => {
      window.removeEventListener("keydown", handleKeyDown);
    };
  }, [onClose]);

  return (
    <div className="fixed inset-0 bg-transparent backdrop-blur-sm bg-opacity-70 flex justify-center items-center z-50">
      <div
        onClick={(e) => e.stopPropagation()}
        className="bg-white rounded-xl shadow-2xl p-8 my-8 w-full max-w-4xl max-h-[95vh] overflow-y-auto relative border border-custom-gray-300"
      >
        <button onClick={onClose} className="cursor-pointer absolute top-4 right-4 text-gray-500 hover:text-black" aria-label="Cerrar">
          <X className="size-5" />
        </button>

        <h2 className="text-2xl font-bold mb-2 text-custom-golden-700">Clonar viaje</h2>
        <p className="text-sm text-custom-gray-500 mb-6">Crea un nuevo viaje copiando los datos del viaje seleccionado. Ajusta la fecha/hora si es necesario.</p>

        <form onSubmit={handleSubmit} className="grid grid-cols-1 md:grid-cols-2 gap-5 text-sm text-custom-black-800">
          <div>
            <label className={labelClass}>Conductor</label>
            <select name="driverId" value={form.driverId} onChange={handleChange} className={inputClass} required>
              <option value="">-- Seleccionar --</option>
              {drivers.map((driver) => (
                <option key={driver.id} value={driver.id}>
                  {driver.email}
                </option>
              ))}
            </select>
            {selectedDriver && (
              <div className="text-xs mt-2 text-custom-gray-700 bg-custom-gray-100 rounded p-3 border border-custom-gray-200">
                <p className="font-medium text-custom-black-800">
                  {selectedDriver.name} {selectedDriver.lastName}
                </p>
                <p className="text-custom-gray-600">{selectedDriver.email}</p>
              </div>
            )}
          </div>

          <div>
            <label className={labelClass}>Origen</label>
            <input name="origin" type="text" value={form.origin as string} onChange={handleChange} className={inputClass} required />
          </div>

          <div>
            <label className={labelClass}>Destino</label>
            <input name="destination" type="text" value={form.destination as string} onChange={handleChange} className={inputClass} required />
          </div>

          <div>
            <label className={labelClass}>Fecha y hora de salida</label>
            <input name="departure" type="datetime-local" value={form.departure as string} onChange={handleChange} className={inputClass} required />
          </div>

          <div>
            <label className={labelClass}>Fecha y hora de llegada</label>
            <input name="arrival" type="datetime-local" value={form.arrival as string} onChange={handleChange} className={inputClass} required />
          </div>

          <div>
            <label className={labelClass}>Zona horaria</label>
            <input name="originalTimeZone" type="text" value={form.originalTimeZone as string} onChange={handleChange} className={inputClass} required />
          </div>

          <div>
            <label className={labelClass}>Ubicación exacta de origen</label>
            <input name="originLocation" type="text" value={form.originLocation as string} onChange={handleChange} className={inputClass} />
          </div>

          <div>
            <label className={labelClass}>Ubicación exacta de destino</label>
            <input name="destinationLocation" type="text" value={form.destinationLocation as string} onChange={handleChange} className={inputClass} />
          </div>

          <div>
            <label className={labelClass}>Tipo de servicio</label>
            <select name="serviceType" value={form.serviceType as TripServiceType} onChange={handleChange} className={inputClass}>
              {Object.values(TripServiceType).map((type) => (
                <option key={type} value={type}>
                  {type}
                </option>
              ))}
            </select>
          </div>

          <div>
            <label className={labelClass}>Estado</label>
            <select name="status" value={form.status as string} onChange={handleChange} className={inputClass}>
              {allowedStatuses.map((status) => (
                <option key={status} value={status}>
                  {status}
                </option>
              ))}
            </select>
          </div>

          <div>
            <label className={labelClass}>Precio base (€)</label>
            <input type="text" name="basePrice" value={String(form.basePrice)} onChange={handleChange} className={inputClass} required />
          </div>

          <div>
            <label className={labelClass}>Capacidad</label>
            <input type="text" name="capacity" value={String(form.capacity ?? "")} onChange={handleChange} className={inputClass} />
          </div>

          <div>
            <label className={labelClass}>Mín. pasajeros</label>
            <input type="text" name="minPassengers" value={String(form.minPassengers ?? "")} onChange={handleChange} className={inputClass} />
          </div>

          <div className="col-span-full flex justify-end gap-3 mt-8">
            <button
              type="button"
              onClick={onClose}
              className="cursor-pointer border border-custom-gray-300 text-custom-black-800 hover:bg-custom-gray-100 font-medium py-2 px-5 rounded-md"
            >
              Cancelar
            </button>
            <button
              type="submit"
              className="cursor-pointer bg-custom-golden-600 hover:bg-custom-golden-700 text-white font-semibold py-2 px-5 rounded-md"
            >
              Clonar viaje
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
