  import React, { Dispatch, SetStateAction, useEffect, useState } from "react";
import { X } from "lucide-react";
import { toast } from "sonner";
import { createTrip } from "@/lib/api/admin/trips";
import { CreateTripRequest, Driver, Partner, TripResponse, TripServiceType, TripStatus } from "@/lib/api/admin/trips/trips.type";
import CityAutocomplete from "@/components/common/CityAutocomplete";
import { DateTime } from "luxon";

interface Props {
    onClose: () => void;
    onSuccess: Dispatch<SetStateAction<TripResponse[]>>;
    partners: Partner[];
    drivers: Driver[];
}

const inputClass =
    "w-full border border-custom-gray-300 rounded-md px-4 py-2 focus:outline-none focus:ring-2 focus:ring-custom-golden-400 transition";
const labelClass = "block text-xs font-semibold text-custom-gray-500 mb-1 uppercase tracking-wide";

// const CreateTripModal = ({ onClose, onSuccess, partners, drivers }: Props) => {
const CreateTripModal = ({ onClose, onSuccess, drivers }: Props) => {
    const [form, setForm] = useState<CreateTripRequest>({
        origin: "",
        destination: "",
        departure: "",
        arrival: "",
        originalTimeZone: "Europe/Madrid",
        serviceType: "SIMPLE_TRIP",
        basePrice: "",
        vehicleId: undefined,
        capacity: undefined,
        minPassengers: undefined,
        autoGenerated: false,
        status: "PENDING",
        originLocation: "",
        destinationLocation: "",
        visible: true,
        // partnerId: "",
        driverId: "",
    });

    // const selectedPartner = partners.find((p) => p.id === form.partnerId);
    const selectedDriver = drivers.find((d) => d.id === form.driverId);
    // const vehicles = selectedPartner?.Vehicle || [];
    // const selectedVehicle = vehicles.find((v) => v.id === form.vehicleId);

    const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => {
        const { name, type, value } = e.target;

        const integerFields = ["capacity", "minPassengers"];
        const decimalFields = ["basePrice"];
        let parsedValue: string | number | boolean = value;

        if (integerFields.includes(name)) {
            if (/^\d*$/.test(value)) {
                parsedValue = value === "" ? "" : Number(value);
            } else {
                return; // ignorar input inválido
            }
        } else if (decimalFields.includes(name)) {
            // Permitir tanto punto como coma como separador decimal
            const normalizedValue = value.replace(/,/g, ".");
            if (/^\d*\.?\d*$/.test(normalizedValue)) {
                parsedValue = normalizedValue;
            } else {
                return; // ignorar input inválido
            }
        } else if (type === "checkbox") {
            parsedValue = (e.target as HTMLInputElement).checked;
        }

        setForm((prev) => ({ ...prev, [name]: parsedValue }));
    };

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        const toastId = toast.loading("Creando viaje...");
        const departureUTC = DateTime.fromISO(form.departure, { zone: "Europe/Madrid" }).toUTC().toISO();
        const arrivalUTC = DateTime.fromISO(form.arrival, { zone: "Europe/Madrid" }).toUTC().toISO();

        const payload = {
            ...form,
            origin: form.origin.trim(),
            destination: form.destination.trim(),
            departure: departureUTC || form.departure,
            arrival: arrivalUTC || form.departure,
            basePrice: parseFloat(form.basePrice as string),
        };

        try {
            const res = await createTrip(payload);

            toast.success("Viaje creado con éxito", { id: toastId });
            onSuccess((prevTrips) => [...prevTrips, res]);
            onClose();
        } catch {
            toast.info("Error al crear el viaje", { id: toastId });
        }
    };

    useEffect(() => {
        const handleKeyDown = (e: KeyboardEvent) => {
            if (e.key === "Escape") {
                onClose(); // función que cierra el modal
            }
        };

        window.addEventListener("keydown", handleKeyDown);
        return () => {
            window.removeEventListener("keydown", handleKeyDown);
        };
    }, [onClose]);

    return (
        <div className="fixed inset-0 bg-transparent backdrop-blur-sm bg-opacity-70 flex justify-center items-center z-50">
            <div
                onClick={(e) => e.stopPropagation()}
                className="bg-white rounded-xl shadow-2xl p-8 my-8 w-full max-w-4xl max-h-[95vh] overflow-y-auto relative border border-custom-gray-300"
            >
                <button onClick={onClose} className="cursor-pointer absolute top-4 right-4 text-gray-500 hover:text-black" aria-label="Cerrar">
                    <X className="size-5" />
                </button>

                <h2 className="text-2xl font-bold mb-2 text-custom-golden-700">Crear nuevo viaje</h2>
                <p className="text-sm text-custom-gray-500 mb-6">Completa los datos a continuación para generar un nuevo viaje.</p>

                <form onSubmit={handleSubmit} className="grid grid-cols-1 md:grid-cols-2 gap-5 text-sm text-custom-black-800">
                    {/* <div className="md:col-span-1">
                        <label className={labelClass}>Partner (Dueño del viaje)</label>
                        <select name="partnerId" value={form.partnerId} onChange={handleChange} className={inputClass}>
                            <option value="">-- Seleccionar --</option>
                            {partners.map((partner) => (
                                <option key={partner.id} value={partner.id}>
                                    {partner.email}
                                </option>
                            ))}
                        </select>
                        {selectedPartner && (
                            <div className="text-xs mt-2 text-custom-gray-700 bg-custom-gray-100 rounded p-3 border border-custom-gray-200">
                                <p className="font-medium text-custom-black-800">
                                    {selectedPartner.name} {selectedPartner.lastName}
                                </p>
                                <p className="text-custom-gray-600">{selectedPartner.email}</p>
                            </div>
                        )}
                    </div> */}

                    <div className="md:col-span-1">
                        <label className={labelClass}>Driver</label>
                        <select name="driverId" value={form.driverId} onChange={handleChange} className={inputClass} required>
                            <option value="">-- Seleccionar --</option>
                            {drivers.map((driver) => (
                                <option key={driver.id} value={driver.id}>
                                    {driver.email}
                                </option>
                            ))}
                        </select>
                        {selectedDriver && (
                            <div className="text-xs mt-2 text-custom-gray-700 bg-custom-gray-100 rounded p-3 border border-custom-gray-200">
                                <p className="font-medium text-custom-black-800">
                                    {selectedDriver.name} {selectedDriver.lastName}
                                </p>
                                <p className="text-custom-gray-600">{selectedDriver.email}</p>
                            </div>
                        )}
                    </div>

                    {/* <div className="col-span-full">
                        <label className={labelClass}>Vehículo</label>
                        <select name="vehicleId" value={form.vehicleId} onChange={handleChange} className={inputClass}>
                            <option value="">{vehicles.length > 0 ? "-- Seleccionar --" : "No tiene vehículos disponibles"}</option>
                            {vehicles.map((v) => (
                                <option key={v.id} value={v.id}>
                                    {v.plate || v.id}
                                </option>
                            ))}
                        </select>
                        {selectedVehicle && (
                            <div className="text-xs mt-2 text-custom-gray-700 bg-custom-gray-100 rounded p-3 border border-custom-gray-200 space-y-1">
                                <p>Capacidad: {selectedVehicle.capacity}</p>
                                <p>Tipo: {selectedVehicle.serviceType}</p>
                                <p>Proveedor: {selectedVehicle.provider}</p>
                                <p>Selección de asientos: {selectedVehicle.allowSeatSelection ? "Sí" : "No"}</p>
                            </div>
                        )}
                    </div> */}

                    <div className="col-span-full">
                        <h3 className="text-base font-semibold text-custom-golden-600 mb-1">Ubicación y horario</h3>
                        <hr className="mb-4" />
                    </div>

                    <div>
                        <label className={labelClass}>Origen</label>
                        <CityAutocomplete
                            value={form.origin}
                            onChange={(val, meta) => {
                                const onlyCity = meta?.payload?.name || (val || "").split(",")[0]?.trim() || val;
                                setForm((prev) => ({ ...prev, origin: onlyCity }));
                            }}
                            placeholder="Ciudad de origen"
                            allowFreeText
                        />
                    </div>

                    <div>
                        <label className={labelClass}>Destino</label>
                        <CityAutocomplete
                            value={form.destination}
                            onChange={(val, meta) => {
                                const onlyCity = meta?.payload?.name || (val || "").split(",")[0]?.trim() || val;
                                setForm((prev) => ({ ...prev, destination: onlyCity }));
                            }}
                            placeholder="Ciudad de destino"
                            allowFreeText
                        />
                    </div>

                    {["departure", "arrival", "originalTimeZone", "originLocation", "destinationLocation"].map((name) => (
                        <div key={name}>
                            <label className={labelClass}>{name}</label>
                            <input
                                name={name}
                                type={name === "departure" || name === "arrival" ? "datetime-local" : "text"}
                                value={
                                    typeof form[name as keyof CreateTripRequest] === "boolean"
                                        ? ""
                                        : (form[name as keyof CreateTripRequest] as string | number) || ""
                                }
                                onChange={handleChange}
                                className={inputClass}
                                required
                            />
                        </div>
                    ))}

                    <div className="col-span-full mt-6">
                        <h3 className="text-base font-semibold text-custom-golden-600 mb-1">Configuración del viaje</h3>
                        <hr className="mb-4" />
                    </div>

                    <div>
                        <label className={labelClass}>Tipo de servicio</label>
                        <select name="serviceType" value={form.serviceType} onChange={handleChange} className={`${inputClass}`} disabled>
                            {Object.values(TripServiceType).map((type) => (
                                <option key={type} value={type}>
                                    {type}
                                </option>
                            ))}
                        </select>
                    </div>

                    <div>
                        <label className={labelClass}>Estado</label>
                        <select name="status" value={form.status} onChange={handleChange} className={inputClass}>
                            {Object.values(TripStatus).map((status) => (
                                <option key={status} value={status}>
                                    {status}
                                </option>
                            ))}
                        </select>
                    </div>

                    <div>
                        <label className={labelClass}>Precio base (€)</label>
                        <input type="text" name="basePrice" value={form.basePrice} onChange={handleChange} className={inputClass} required />
                    </div>

                    <div>
                        <label className={labelClass}>Capacidad</label>
                        <input type="text" name="capacity" value={form.capacity ?? ""} onChange={handleChange} className={inputClass} />
                    </div>

                    <div>
                        <label className={labelClass}>Mín. pasajeros</label>
                        <input type="text" name="minPassengers" value={form.minPassengers ?? ""} onChange={handleChange} className={inputClass} />
                    </div>

                    <div className="col-span-full flex flex-wrap items-center gap-6 mt-2">
                        {/* <label className="flex items-center text-xs font-medium">
                            <input type="checkbox" name="autoGenerated" checked={form.autoGenerated} onChange={handleChange} className="mr-2" />
                            Auto-generado
                        </label> */}
                        <label className="flex items-center text-xs font-medium">
                            <input type="checkbox" name="visible" checked={form.visible} onChange={handleChange} className="mr-2" />
                            Visible al público
                        </label>
                    </div>

                    <div className="col-span-full flex justify-end gap-3 mt-8">
                        <button
                            type="button"
                            onClick={onClose}
                            className="cursor-pointer border border-custom-gray-300 text-custom-black-800 hover:bg-custom-gray-100 font-medium py-2 px-5 rounded-md"
                        >
                            Cancelar
                        </button>
                        <button
                            type="submit"
                            className="cursor-pointer bg-custom-golden-600 hover:bg-custom-golden-700 text-white font-semibold py-2 px-5 rounded-md"
                            disabled={!form.driverId || !form.origin || !form.destination}
                        >
                            Crear viaje
                        </button>
                    </div>
                </form>
            </div>
        </div>
    );
};

export default CreateTripModal;
