"use client";

import { TripReservation } from "@/lib/api/admin/trips/trips.type";
import { X } from "lucide-react";
import { DateTime } from "luxon";
import { useEffect } from "react";

interface TripDetailsModalProps {
    trip: {
        id: string;
        basePrice: number;
        origin: string;
        destination: string;
        departure: string;
        arrival: string;
        originalTimeZone: string;
        originLocation: string;
        destinationLocation: string;
        serviceType: string;
        vehicleId: string | null;
        capacity: number;
        minPassengers: number;
        status: string;
        autoGenerated: boolean;
        createdAt: string;
        reservations: TripReservation[];
    };
    onClose: () => void;
}

const TripDetailsModal = ({ trip, onClose }: TripDetailsModalProps) => {
    const departure = DateTime.fromISO(trip.departure).setZone(trip.originalTimeZone);
    const arrival = DateTime.fromISO(trip.arrival).setZone(trip.originalTimeZone);

    useEffect(() => {
        const handleKeyDown = (e: KeyboardEvent) => {
            if (e.key === "Escape") {
                onClose(); // función que cierra el modal
            }
        };

        window.addEventListener("keydown", handleKeyDown);
        return () => {
            window.removeEventListener("keydown", handleKeyDown);
        };
    }, [onClose]);

    return (
        <div onClick={onClose} className="fixed inset-0 bg-transparent backdrop-blur-sm bg-opacity-70 flex justify-center items-center z-50">
            <div
                onClick={(e) => e.stopPropagation()}
                className="bg-white rounded-xl shadow-lg p-6 w-full max-w-3xl relative border border-custom-gray-300"
            >
                <button onClick={onClose} className="cursor-pointer absolute top-4 right-4 text-gray-600 hover:text-black">
                    <X className="size-5" />
                </button>
                <h2 className="text-2xl font-bold mb-6 text-custom-golden-700">Detalles del viaje</h2>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-sm text-custom-black-800 mb-6">
                    <div className="bg-custom-white-50 p-3 rounded-md border border-custom-gray-200">
                        <label className="block text-xs font-semibold text-custom-gray-500 mb-1">Origen</label>
                        <p>{trip.originLocation}</p>
                    </div>

                    <div className="bg-custom-white-50 p-3 rounded-md border border-custom-gray-200">
                        <label className="block text-xs font-semibold text-custom-gray-500 mb-1">Destino</label>
                        <p>{trip.destinationLocation}</p>
                    </div>

                    <div className="bg-custom-white-50 p-3 rounded-md border border-custom-gray-200">
                        <label className="block text-xs font-semibold text-custom-gray-500 mb-1">Salida</label>
                        <p>{departure.toLocaleString(DateTime.DATETIME_MED)}</p>
                    </div>

                    <div className="bg-custom-white-50 p-3 rounded-md border border-custom-gray-200">
                        <label className="block text-xs font-semibold text-custom-gray-500 mb-1">Llegada</label>
                        <p>{arrival.toLocaleString(DateTime.DATETIME_MED)}</p>
                    </div>

                    <div className="bg-custom-white-50 p-3 rounded-md border border-custom-gray-200">
                        <label className="block text-xs font-semibold text-custom-gray-500 mb-1">Precio base</label>
                        <p>€ {trip.basePrice.toFixed(2)}</p>
                    </div>

                    <div className="bg-custom-white-50 p-3 rounded-md border border-custom-gray-200">
                        <label className="block text-xs font-semibold text-custom-gray-500 mb-1">Capacidad</label>
                        <p>{trip.capacity} pasajeros</p>
                    </div>
                </div>

                <h3 className="text-lg font-semibold text-custom-black-900 mb-2">Reservas</h3>
                {trip.reservations.length === 0 ? (
                    <p className="text-sm text-custom-gray-600 italic mb-4">No hay reservas para este viaje.</p>
                ) : (
                    <div className="overflow-x-auto border border-custom-gray-200 rounded-xl bg-white">
                        <table className="min-w-full text-sm text-left">
                            <thead className="bg-custom-golden-100 text-custom-golden-800">
                                <tr>
                                    <th className="px-4 py-3">Nombre</th>
                                    <th className="px-4 py-3">Correo</th>
                                    <th className="px-4 py-3">Método de pago</th>
                                    <th className="px-4 py-3">Estado</th>
                                </tr>
                            </thead>
                            <tbody>
                                {trip.reservations.map((res) => (
                                    <tr key={res.id} className="border-t border-custom-gray-100 hover:bg-custom-golden-50">
                                        <td className="px-4 py-3">{`${res.user?.name ?? ""} ${res.user?.lastName ?? ""}`.trim()}</td>
                                        <td className="px-4 py-3">{res.user?.email ?? "-"}</td>
                                        <td className="px-4 py-3">{res.paymentMethod}</td>
                                        <td className="px-4 py-3">
                                            <span
                                                className={`px-2 py-1 rounded-full text-xs font-semibold ${
                                                    res.status === "CONFIRMED"
                                                        ? "bg-green-100 text-green-700"
                                                        : res.status === "PENDING"
                                                        ? "bg-yellow-100 text-yellow-700"
                                                        : "bg-red-100 text-red-700"
                                                }`}
                                            >
                                                {res.status}
                                            </span>
                                        </td>
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    </div>
                )}

                <div className="mt-6 flex justify-end">
                    <button
                        onClick={onClose}
                        className="border border-custom-gray-300 text-custom-black-800 hover:bg-custom-gray-100 font-medium py-2 px-4 rounded-md"
                    >
                        Cerrar
                    </button>
                </div>
            </div>
        </div>
    );
};

export default TripDetailsModal;
