"use client";

import React, { useEffect, useState } from "react";
import { useSearchParams } from "next/navigation";
import { DateTime } from "luxon";
import { CalendarDays, Clock } from "lucide-react";
import { getTripById } from "@/lib/api/driver-profile/intex";
import { TripDetailsResponse } from "@/lib/api/driver-profile/driverProfile.types";
import { Passengers } from "@/lib/api/admin/trips/trips.type";

const TripDetailsPage = () => {
  const searchParams = useSearchParams();
  const id = searchParams.get("id");
  const [trip, setTrip] = useState<TripDetailsResponse | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (!id) return;
    type ValidStatus = "PENDING" | "CONFIRMED" | "CANCELLED";

    const fetchTrip = async () => {
      try {
        const raw = (await getTripById(id as string)) as TripDetailsResponse;

        const mapped: TripDetailsResponse = {
          id: raw.id,
          basePrice: raw.basePrice,
          origin: raw.origin,
          destination: raw.destination,
          departure: raw.departure,
          arrival: raw.arrival,
          originalTimeZone: raw.originalTimeZone,
          originLocation: raw.originLocation,
          destinationLocation: raw.destinationLocation,
          status: raw.status,
          capacity: raw.capacity,
          minPassengers: raw.minPassengers,
          passengers: (raw.reservations || []).map((res: Passengers) => {
            const validStatuses: ValidStatus[] = [
              "PENDING",
              "CONFIRMED",
              "CANCELLED",
            ];
            const status: ValidStatus = validStatuses.includes(
              res.status as ValidStatus
            )
              ? (res.status as ValidStatus)
              : "PENDING";
            return {
              id: res.id,
              userId: res.user?.id ?? "",
              fullName: `${res.user?.name ?? ""} ${
                res.user?.lastName ?? ""
              }`.trim(),
              email: res.user?.email ?? "Sin email",
              paymentMethod: res.paymentMethod,
              status,
              qr: res.qr ?? null,
            };
          }),
          serviceType: raw.serviceType,
          vehicleId: raw.vehicleId,
          autoGenerated: raw.autoGenerated,
          createdAt: raw.createdAt,
        };

        setTrip(mapped);
      } catch (error) {
        console.error("Error al cargar el viaje:", error);
      } finally {
        setLoading(false);
      }
    };

    fetchTrip();
  }, [id]);

  if (loading) return <div className="p-6">Cargando detalles del viaje...</div>;
  if (!trip) return <div className="p-6">Viaje no encontrado.</div>;

  const departure = DateTime.fromISO(trip.departure).setZone(
    trip.originalTimeZone
  );
  const arrival = DateTime.fromISO(trip.arrival).setZone(trip.originalTimeZone);

  return (
    <div className="w-full max-w-7xl mx-auto p-4 md:p-6">
      <h1 className="text-2xl font-bold mb-6 text-custom-black-900">
        Detalles del viaje
      </h1>

      <div className="bg-custom-white-100 shadow-md rounded-xl p-6 border border-custom-gray-200">
        <h2 className="text-xl font-semibold text-custom-black-900 mb-1">
          {trip.origin} → {trip.destination}
        </h2>
        <p className="text-sm text-custom-gray-500 mb-4">
          {trip.originLocation} — {trip.destinationLocation}
        </p>

        <div className="flex items-center gap-2 mb-2 text-custom-gray-700 text-sm">
          <CalendarDays className="size-4" />
          <span>{departure.setLocale("es").toFormat("cccc, d 'de' LLLL")}</span>
        </div>

        <div className="flex items-center gap-2 mb-2 text-custom-gray-700 text-sm">
          <Clock className="size-4" />
          <span>
            {departure.toFormat("HH:mm")} — {arrival.toFormat("HH:mm")}
          </span>
        </div>

        <p className="text-sm text-custom-gray-700">
          <strong>Estado del viaje:</strong> {trip.status}
        </p>
        <p className="text-sm text-custom-gray-700">
          <strong>Capacidad:</strong> {trip.capacity} — <strong>Mínimo:</strong>{" "}
          {trip.minPassengers}
        </p>
        <p className="text-sm text-custom-gray-700 mt-2">
          <strong>Precio base:</strong> {trip.basePrice.toFixed(2)} €
        </p>
      </div>

      <div className="mt-8">
        <h3 className="text-lg font-semibold text-custom-black-900 mb-3">
          Pasajeros
        </h3>
        {trip.passengers.length === 0 ? (
          <p className="text-sm text-custom-gray-600 italic">
            No hay pasajeros en este viaje aún.
          </p>
        ) : (
          <div className="overflow-x-auto border border-custom-gray-200 rounded-xl bg-white">
            <table className="min-w-full text-sm text-left">
              <thead className="bg-custom-golden-100 text-custom-golden-800">
                <tr>
                  <th className="px-4 py-3">Nombre</th>
                  <th className="px-4 py-3">Correo</th>
                  <th className="px-4 py-3">Método de pago</th>
                  <th className="px-4 py-3">Estado</th>
                  <th className="px-4 py-3">Abordaje</th>
                </tr>
              </thead>
              <tbody>
                {trip.passengers.map((passenger) => (
                  <tr
                    key={passenger.id}
                    className="border-t border-custom-gray-100 hover:bg-custom-golden-50">
                    <td className="px-4 py-3">{passenger.fullName}</td>
                    <td className="px-4 py-3">{passenger.email}</td>
                    <td className="px-4 py-3">{passenger.paymentMethod}</td>
                    <td className="px-4 py-3">
                      <span
                        className={`px-2 py-1 rounded-full text-xs font-semibold ${
                          passenger.status === "CONFIRMED"
                            ? "bg-green-100 text-green-700"
                            : passenger.status === "PENDING"
                            ? "bg-yellow-100 text-yellow-700"
                            : "bg-red-100 text-red-700"
                        }`}>
                        {passenger.status}
                      </span>
                    </td>
                    <td className="px-4 py-3">
                      {passenger.qr && !passenger.qr.isDeleted ? (
                        !passenger.qr.isValid && passenger.qr.usedAt ? (
                          <span className="text-green-700 font-medium">
                            Abordó
                          </span>
                        ) : (
                          <span className="text-yellow-700">Pendiente</span>
                        )
                      ) : (
                        <span className="text-red-600">QR inválido</span>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
};

export default TripDetailsPage;
